sudo: true
dist: trusty
language: go
go:
  - 1.9.4

os:
  - linux

services:
  - docker
env:
  global:
  - GOX_FLAGS="-arch amd64"
  - DOCKER_IMAGE=alectolytic/rpmbuilder
  - COPR_REPOSITORY=alexbmasis/sqlbeat
  - OS_ARCH=x86_64
  matrix:
  - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=27
  - OS_TYPE=centos OS_DIST=epel OS_VERSION=7

addons:
  apt:
    packages:
    - python-virtualenv
before_install:
  # Redo the travis setup but with the elastic/libbeat path. This is needed so the package path is correct
  - sudo apt-get -qq update
  - mkdir -p $HOME/gopath/src/github.com/abraverm/sqlbeat
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/abraverm/sqlbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/abraverm/sqlbeat
  - cd $HOME/gopath/src/github.com/abraverm/sqlbeat
  - go get github.com/Masterminds/glide

install: true

script:
  - make update-deps
  - make check
  - make testsuite
  - go build
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z  ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}

after_success:
  - pip install --upgrade pip
  - pip install requests[security]
  - pip install copr-cli simplejson
  - openssl aes-256-cbc -K $encrypted_52ba645f9e60_key -iv $encrypted_52ba645f9e60_iv -in .copr.enc -out .copr -d
  - if [ ! -z "${TRAVIS_TAG}" ]; then copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY} *.src.rpm; fi
